#name: cwms
volumes:
  oracle_data:
services:
  db:
    # if using gvenzl/oracle-xe you'll need to adjust the environment below
    image: ${ORACLE_DOCKER_IMAGE}
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      - ORACLE_PDB=CWMS
      - ORACLE_PWD=badSYSpassword
      - ORACLE_EDITION=enterprise
    ports:
      - 1521
    healthcheck:
      test: ["CMD","tnsping", "CWMS"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40m
  db_install:
    depends_on:
      db:
        condition: service_healthy
    image: ${CWMS_SCHEMA_INSTALLER_IMAGE:-registry.hecdev.net/cwms/schema_installer:23.03.16}
    pull_policy: always
    tty: true
    environment:
      - DB_HOST_PORT=db:1521
      - DB_NAME=/CWMS
      - CWMS_PASSWORD=simplecwmspasswD1
      - SYS_PASSWORD=badSYSpassword
      # set to HEC/q0 for any national system work
      - OFFICE_ID=HEC
      - OFFICE_EROC=q0
      - INSTALLONCE=1
      - QUIET=1
    restart: "no"

  db_webuser_permissions:
    image: ${CWMS_SCHEMA_INSTALLER_IMAGE:-registry.hecdev.net/cwms/schema_installer:23.03.16}
    restart: "no"
    environment:
      - DB_HOST_PORT=db:1521
      - DB_NAME=/CWMS
      - CWMS_PASSWORD=simplecwmspasswD1
      - SYS_PASSWORD=badSYSpassword
      # set to HQ/q0 for any national system work
      - OFFICE_ID=HQ
      - OFFICE_EROC=q0
      - INSTALLONCE=1
      - QUIET=1
    command: >
      sh -xc "echo \"begin cwms_sec.add_user_to_group('$${OFFICE_EROC}webtest','CWMS Users', 'HQ'); cwms_sec.add_user_to_group('$${OFFICE_EROC}webtest','CWMS User Admins', 'HQ'); end;\" > /tmp/sql.sql &&
                     echo "/" >> /tmp/sql.sql
                     echo "quit" >> /tmp/sql.sql
                    sqlplus CWMS_20/$$CWMS_PASSWORD@$$DB_HOST_PORT$$DB_NAME @/tmp/sql"
    depends_on:
      db:
        condition: service_healthy
      db_install:
        condition: service_completed_successfully


  data-api:
    depends_on:
      db:
        condition: service_healthy
      db_install:
        condition: service_completed_successfully
      db_webuser_permissions:
        condition: service_completed_successfully
      traefik:
        condition: service_healthy
    image: cwms-rest-api:2.6-compose
    build:
      target: api
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - RADAR_JDBC_URL=jdbc:oracle:thin:@db/CWMS
      - RADAR_JDBC_USERNAME=q0webtest
      - RADAR_JDBC_PASSWORD=simplecwmspasswD1
    expose:
      - 7000
    healthcheck:
      test: ["CMD","/usr/bin/curl", "-I","localhost:7000/cwms-data/offices/HEC"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.data-api.rule=Host(`cwms-data.localhost`)"
      - "traefik.http.routers.data-api.entryPoints=web"

  #auth:
  #  image: authelia/authelia:4.37.5
  #  restart: unless-stopped
  # Proxy for HTTPS for OpenID
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      #- "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:81"
      - "--ping"
    ports:
      - "81:81"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    healthcheck:
      test: traefik healthcheck --ping