name: Build CWMS RADAR
on:   
  push:
    branches:
      - main
  pull_request:
    branches: 
      - develop

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build and test     
        uses: actions/setup-java@v1
        with:
          java-verson: '11'
          java-package: jdk             
        run: ./gradlew test