name: Create Release
on:   
  push-rqeuest:
    branches: 
      - develop

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build and test
        run: ./gradlew test