name: Build CWMS RADAR
on:   
  push:
    branches:
      - main
  pull_request:
    branches: 
      - develop

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk             
      - name: build and test     
        run: ./gradlew test
      - name: Build docker image
        run: ./gradlew dockerBuild